server:
  port: 9190
logging:
  level:
    com.hula.service.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread]-[%-3level ]-[tid：%X{tid}]-[%c]：%L：%m%n"
spring:
  # 使用的配置文件
  profiles:
    active: dev
  application:
    name: hula
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${HuLa-IM.HOST}:${HuLa-IM.MYSQL_PORT}/${HuLa-IM.DATABASE_NAME}?serverTimezone=GMT%2b8
    username: ${HuLa-IM.MYSQL_USER_NAME}
    password: ${HuLa-IM.MYSQL_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    hikari: # 配置(毫秒)
      auto-commit: true #是否默认提交事务 (默认值：true)
      idle-timeout: 10000 #控制连接在池中允许空闲的最长时间
      connection-timeout: 30000 #请求连接的超时时间
      maximum-pool-size: 20 #最大连接数
      minimum-idle: 5 #最小空闲连接数量
      max-lifetime: 1800000 #连接的最长生命周期
      keepalive-time: 1750000 #尝试保持连接的频率
      connection-test-query: select 1 #连接验证sql
      pool-name: HikariCP-hula
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  #redis配置
  data:
    redis:
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器地址
      host: ${HuLa-IM.HOST}
      # Redis服务器连接端口
      port: ${HuLa-IM.REDIS.PORT}
      # Redis服务器连接密码（默认为空）
      password: ${HuLa-IM.REDIS.PAW}
      # 连接超时时间
      timeout: 1800000

  # rabbitmq配置
  rabbitmq:
    host: ${HuLa-IM.RABBITMQ.HOST:localhost}
    port: ${HuLa-IM.RABBITMQ.PORT:5672}
    username: ${HuLa-IM.RABBITMQ.USERNAME:guest}
    password: ${HuLa-IM.RABBITMQ.PASSWORD:guest}
    virtual-host: ${HuLa-IM.RABBITMQ.VIRTUAL-HOST:/}
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 1
        max-concurrency: 5

  # jackson配置
  jackson:
    serialization:
      write-dates-as-timestamps: true # 序列化
    date-format: yyyy-MM-dd HH:mm:ss # 日期格式化
    deserialization:
      fail-on-unknown-properties: false # false表示处理多余字段不抛异常

#mybatis-plus 配置
mybatis-plus:
  global-config:
    banner: false # 关闭MP图案打印
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 微信扫码配置
wx:
  mp:
    callback: ${HuLa-IM.WX.CALLBACK}
    configs:
      - appId: ${HuLa-IM.WX.APPID} # 第一个公众号的appid
        secret: ${HuLa-IM.WX.SECRET} # 公众号的appsecret
        token: ${HuLa-IM.WX.TOKEN} # 接口配置里的Token值
        aesKey: ${HuLa-IM.WX.AESKEY} # 接口配置里的EncodingAESKey值
# JWT
jwt:
  secret: ${HuLa-IM.JWT.SECRET}

# doc配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'core'
      paths-to-match: '/**'
      packages-to-scan: com.hula.core
knife4j:
  # 开启增强配置
  enable: true
  setting:
    language: zh_cn

public:
  urls:
    - /system/config/init
    - /token/login
    - /token/refreshToken
    - /token/register
